### PR TITLE
Extend Prolog filetype with Visual Prolog keywords

### PR DESCRIPTION
**Pull request by rdipardo**
Lexilla's lexer was specially written for Visual Prolog.
The difference between that and SWI-Prolog is much like Delphi
vis-à-vis Standard Pascal: an object-oriented superset of the
language, mainly intended for Windows application development.

This adds a list of the most common Visual Prolog keywords,
copied from these sources:

- https://wiki.visual-prolog.com/index.php?title=Language_Reference/Built-in_entities#Predicates
- https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/visualprolog.properties

### CODE REVIEW

**Comment by rdipardo** [comment]
geany_visualprolog_ft_with_domains

**Comment by techee** [comment]
Cool, thanks, will add those. I haven't checked but does it also include all the previous keywords so SWI is fully covered? (Despite being written for VisualProlog, I think most people will use it for SWI.)

**Comment by rdipardo** [comment]
> does it also include all the previous keywords so SWI is fully covered?

SWI-Prolog defines an impossible number of predicates if you consider the [many, many libraries](https://www.swi-prolog.org/pldoc/man?section=libpl) included in a typical distribution. Parity with [prolog.vim] is good enough, and already much better than what [SciTE][0] and [Notepad++][1] provide.

[0]: https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/visualprolog.properties
[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/292c057f655ec5e691d92045ab78c24c01b8b102/PowerEditor/src/langs.model.xml#L392-L397
[prolog.vim]: https://github.com/yochem/prolog.vim/blob/master/syntax/prolog.vim

**Comment by techee** [comment]
> Parity with [prolog.vim](https://github.com/yochem/prolog.vim/blob/master/syntax/prolog.vim) is good enough

That's basically what I meant, whether you kept the keywords I originally added from vim.

> and already much better than what [SciTE](https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/visualprolog.properties) and [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/292c057f655ec5e691d92045ab78c24c01b8b102/PowerEditor/src/langs.model.xml#L392-L397) provide.

Oh, I completely forgot about SciTE when searching for where to take the keywords from - should have been my first choice.

**Comment by rdipardo** [comment]
> > Parity with [prolog.vim](https://github.com/yochem/prolog.vim/blob/master/syntax/prolog.vim) is good enough
> 
> That's basically what I meant, whether you kept the keywords I originally added from vim.

Everything is still there, yes. But, on second thoughts, there's an excellent [VS Code extension] for Prolog with more [comprehensive coverage][0] of builtin predicates. Maybe the "primary" set could be based on that instead?
 
[VS Code extension]: https://github.com/arthwang/vsc-prolog
[0]:
https://github.com/arthwang/vsc-prolog/blob/3fab7b5916c505d55efc1b7556249bbe2d929dda/syntaxes/prolog.ecl.tmLanguage.json#L202-L205

**Comment by rdipardo** [comment]
Looks like this is already in good hands: https://github.com/geany/geany/pull/3171

**Pull request closed without merging**
